version: "3.7"

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ts-graphql
      POSTGRES_PASSWORD: ts-graphql
      POSTGRES_DB: ts-graphql
